### PR TITLE
Switch to Irony.NetCore on NuGet - don't use MyGet anymore.

### PR DESCRIPTION
**Pull request by igitur**
and Upgrade MSTest adapters.

### CODE REVIEW

**Comment by igitur** [comment]
@dhoepelman If you merge this and update a new NuGet version, you'll have to update the dependencies in the NuGet specs too. Switch from `Irony` to `Irony.NetCore`.

**Comment by igitur** [comment]
@dhoepelman Mind looking at this PR?

**Comment by igitur** [comment]
@dhoepelman Or please grant @roelvandersteen access to this repo so that we can consolidate his fork into this one.

**Comment by dhoepelman** [comment]
Merging this because @roelvandersteen already published this in 1.3.2

**Comment by igitur** [comment]
On the other hand, I just learnt that spreadsheetlab is an actual real-life organisation. So if this project is taken forward by the community, maybe @roelvandersteen 's repo should be the primary one. @roelvandersteen , please add your comment.

**Pull request merged**
