### PR TITLE
Multitargeting, including .NET Standard 1.6

### LINKED ISSUE #60: .NET Standard support
Any plans to implement .NET Standard?

Context: We at http://github.com/ClosedXML/ClosedXML would like to use XLParser to parse the Excel formulae, but are planning to support .NET Standard.

### PR DESCRIPTION
**Pull request by igitur**
Fairly large PR that does a few things. I hope to lay it out clearly in the steps below, but the gist of it is that it upgrades the project for multi-targeting.

- Removes the Irony library from source control
- References the [daxnet build](https://github.com/daxnet/irony) of Irony
- Adds @daxnet 's MyGet repo reference in `NuGet.config` file
- Upgrades the `csproj` files to VS2017 format.
- Remove `AssemblyInfo.cs` files as this info is populated in the `.csproj` files now.
- Change targets to `net452`, `net461`, and `netstandard1.6`. 
- Use compilation directives for a few workarounds for supporting multiple targets.

Please let me know if I need to explain in more detail or if you require any changes.

Fixes #60

### CODE REVIEW

**Comment by igitur** [comment]
@dhoepelman ?

**Comment by dhoepelman** [comment]
Hi @igitur, thanks for the PR, seems like a needed update.

@aivaloglou Do you still use this project in production in infotron? If so I suggest you review and merge it, otherwise, I'll take a look at it and think of a more permanent solution for maintaing the project.

**Comment by dhoepelman** [comment]
Thanks @igitur !

**Comment by igitur** [comment]
Thanks for merging. Do I understand correctly that you're not actively developing this library anymore? If so, would you still actively review pull requests? Else I'll just fork and maintain on my own For ClosedXML 's purposes.

**Comment by dhoepelman** [comment]
@igitur That's correct, not actively developing at the moment. Will still review PR's. You are of course free to fork, but if you are interested in doing some more development you could also get commit access to this repo & publish rights for nuget.

**Comment by igitur** [comment]
@dhoepelman Does that offer still stand? I'd like to consolidate the forks.

**Pull request merged**
