### PR TITLE
Correct NamedRangeCombinationToken

### LINKED ISSUE #46: Failed parsing named range
Formula:

IF(A2.PART_NUM<>"",(IF(AND(A2.PART_NUM=1),"CO","AP")),"")

does not parse because of named range A2.PART_NUM

### PR DESCRIPTION
**Pull request by dhoepelman**
Corrects characters allowed following the start word in NamedRangeCombinationToken

Fixes #46

### CODE REVIEW

**Comment by dhoepelman** [comment]
Don't merge this, contains a pretty big error

**Comment by dhoepelman** [comment]
Okay now it does what it's supposed to again

**Comment by aivaloglou** [comment]
Named ranges identification has become very complex! Which is normal, considering all the strange cases the rules have to cover. This seems to address everything we came across so far. Merging in.

**Comment by dhoepelman** [comment]
Yeah it has been. It might be worth creating our own Irony token which does exactly what the Excel spec does, it might even be clearer than what we currently have.

**Pull request merged**
